/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavesNewRouteImport } from './routes/saves.new'
import { Route as SavesIdRouteImport } from './routes/saves.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesNewRoute = SavesNewRouteImport.update({
  id: '/saves/new',
  path: '/saves/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesIdRoute = SavesIdRouteImport.update({
  id: '/saves/$id',
  path: '/saves/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saves/$id': typeof SavesIdRoute
  '/saves/new': typeof SavesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saves/$id': typeof SavesIdRoute
  '/saves/new': typeof SavesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saves/$id': typeof SavesIdRoute
  '/saves/new': typeof SavesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/saves/$id' | '/saves/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/saves/$id' | '/saves/new'
  id: '__root__' | '/' | '/saves/$id' | '/saves/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavesIdRoute: typeof SavesIdRoute
  SavesNewRoute: typeof SavesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves/new': {
      id: '/saves/new'
      path: '/saves/new'
      fullPath: '/saves/new'
      preLoaderRoute: typeof SavesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves/$id': {
      id: '/saves/$id'
      path: '/saves/$id'
      fullPath: '/saves/$id'
      preLoaderRoute: typeof SavesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavesIdRoute: SavesIdRoute,
  SavesNewRoute: SavesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
